pipeline {
  agent {
        node {
          label 'nodejs' 
        }
  }
  options {
        timeout(time: 20, unit: 'MINUTES') 
  }
  stages {
        stage('build') {
                steps {
                         openshiftBuild(buildConfig: 'nodejs-mongodb-example', showBuildLogs: 'true')
                }
        }
        stage('deploy') {
                steps {
                          openshiftDeploy(deploymentConfig: 'nodejs-mongodb-example')
                }
        }
  }
}
